"""
Session E closing study -- the headline comparison of the project.

Fit vanilla Heston (Phase 1) and lifted rough Heston (Phase 2) by the same
Levenberg-Marquardt driver to the same market, then compare the ATM skew term
structure of market, Heston and rough Heston. Two markets, because they answer
different questions:

  IN-MODEL      generated by rough Heston itself at H = 0.12. The truth is in
                the rough model's class, so the rough fit must recover it and
                the question is purely whether vanilla Heston CAN follow.
  STYLISED      the Phase 1 surface (capture_calibration.rough_iv): a smile
                with ATM skew tau^(H - 1/2), H = 0.12, written down directly.
                Neither model contains it; the question is which gets closer.

Every table and figure is keyed by maturity. An earlier version aligned the
model curves to the market by nearest neighbour and zipped per-expiry reports
of unequal length, so a maturity the model failed to price showed up as a copy
of its neighbour (-1.2574 at 14, 30, 60 and 90 days) or vanished. Missing is
now printed as a dash and drawn as a gap.

Writes docs/phase2_rough_vs_heston.md and captures/rough_vs_heston.png.

    python capture_rough_vs_heston.py
"""

import math
import pathlib
import time

import numpy as np

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

import volsurf_core as vc
import pricing.fourier as fo
import models.rough_heston as rh
from models.heston import HestonParams
from calibrate.objective import MarketSurface, per_expiry_report
from calibrate.fit import (DEFAULT_STARTS, calibrate_heston, calibrate_rough_heston,
                           heston_cf_factory)
from capture_calibration import H_TRUE, atm_vol, rough_iv

OUT = pathlib.Path(__file__).parent / "captures"
OUT.mkdir(exist_ok=True)
DOC = pathlib.Path(__file__).parent / "docs" / "phase2_rough_vs_heston.md"

TRUE = rh.RoughHestonParams(0.04, 2.0, 0.045, 0.5, -0.7, H_TRUE)
FIT_DAYS = (1, 2, 3, 7, 14, 30, 90, 365)
SKEW_DAYS = (1, 2, 3, 5, 7, 10, 14, 30, 60, 90, 180, 365)
SHORT_END = 14                      # days: the log-log slope is read up to here
N_K = 7
ROUGH_START = rh.RoughHestonParams(0.04, 2.0, 0.04, 0.5, -0.5, 0.25)

# Weighting. See study_h_identifiability.py: with vega^2 weights from a price
# half-spread, the short maturities -- where H lives -- carry almost no weight,
# and H is not identified. The comparison is made with every quote weighted
# equally in vol, the same for both models.
WEIGHTING = "equal-in-vol"


def band(tau, n_sigma=3.0):
    return n_sigma * atm_vol(tau) * math.sqrt(tau)


def surface_from(iv_strip, days=FIT_DAYS, n_k=N_K):
    T, K, V, W = [], [], [], []
    for d in days:
        tau = d / 365.0
        ks = np.linspace(-band(tau), band(tau), n_k)
        ivs = np.asarray(iv_strip(ks, tau), dtype=float)
        for k, v in zip(ks, ivs):
            if not np.isfinite(v):
                continue
            T.append(tau)
            K.append(float(k))
            V.append(float(v))
            W.append(1.0)
    return MarketSurface(np.array(T), np.array(K), np.array(V), np.array(W))


def stylised_strip(ks, tau):
    return np.array([rough_iv(k, tau) for k in ks])


def rough_strip(p, steps_mult=1.0):
    def f(ks, tau):
        c, info = rh.call_prices(np.asarray(ks, dtype=float), tau, p, steps_mult=steps_mult)
        return fo.implied_vols_from_calls(c, np.asarray(ks, dtype=float), tau)
    return f


def heston_strip(p):
    def f(ks, tau):
        ks = np.asarray(ks, dtype=float)
        c = np.atleast_1d(fo.carr_madan_call(ks, tau, heston_cf_factory(p, tau)))
        return fo.implied_vols_from_calls(c, ks, tau)
    return f


def skews(strip, days=SKEW_DAYS, n_k=41):
    """{day: ATM skew d(sigma)/dk} -- a missing day is simply absent."""
    out = {}
    for d in days:
        tau = d / 365.0
        ks = np.linspace(-band(tau), band(tau), n_k)
        vs = np.asarray(strip(ks, tau), dtype=float)
        ok = np.isfinite(vs)
        if ok.sum() < 8:
            continue
        zs = ks[ok] / (atm_vol(tau) * math.sqrt(tau))
        s, _, _ = vc.atm_skew_from_slice(ks[ok], vs[ok], zs=zs, window=1.5)
        if s is not None and np.isfinite(s):
            out[d] = float(s)
    return out


def loglog_slope(sk, max_days=SHORT_END):
    ds = sorted(d for d in sk if d <= max_days)
    if len(ds) < 3:
        return float("nan")
    x = np.log(np.array(ds) / 365.0)
    y = np.log(np.abs(np.array([sk[d] for d in ds])))
    return float(np.polyfit(x, y, 1)[0])


def local_slope(sk, a, b):
    """log-log slope between two maturities; NaN if either is missing."""
    if a not in sk or b not in sk:
        return float("nan")
    return math.log(abs(sk[b] / sk[a])) / math.log(b / a)


def fmt(v, spec="9.4f"):
    return f"{v:{spec}}" if v is not None and np.isfinite(v) else "—".rjust(int(spec.split('.')[0]))


def run_market(label, S):
    print(f"\n=== {label}: {len(S)} quotes, {S.n_expiries} expiries ===")
    t0 = time.perf_counter()
    r_h = calibrate_heston(S, starts=DEFAULT_STARTS[:2], max_iter=60, max_seconds=180)
    print(f"  Heston : rmse {r_h['rmse_vol']*100:.3f} vp  ({time.perf_counter()-t0:.0f}s)  "
          + "  ".join(f"{n}={getattr(r_h['params'], n):.4f}" for n in HestonParams.NAMES), flush=True)
    t0 = time.perf_counter()
    r_r = calibrate_rough_heston(S, starts=(ROUGH_START,), max_iter=60, max_seconds=2400,
                                 callback=lambda it, x, cost, lam:
                                 print(f"     it {it:2d} cost {cost:.4e} lam {lam:.1e}", flush=True))
    print(f"  rough  : rmse {r_r['rmse_vol']*100:.3f} vp  ({time.perf_counter()-t0:.0f}s, "
          f"{r_r['iterations']} it, {r_r['reason']})  "
          + "  ".join(f"{n}={getattr(r_r['params'], n):.4f}" for n in rh.RoughHestonParams.NAMES),
          flush=True)
    print(f"           pricer {r_r['pricer_stats']}; kernel error at fitted H {r_r['kernel_error']:.2%}")
    return r_h, r_r


def by_tau(report):
    return {int(round(row["tau"] * 365)): row for row in report}


def main():
    markets = {}

    # In-model market: generated by rough Heston at a tighter solve than any fit uses
    t0 = time.perf_counter()
    S_in = surface_from(rough_strip(TRUE, steps_mult=2.0))
    print(f"in-model market built in {time.perf_counter()-t0:.0f}s")
    S_st = surface_from(stylised_strip)

    results = {}
    for key, label, S, market_strip in (("in", "IN-MODEL market (rough Heston, H = 0.12)", S_in,
                                         rough_strip(TRUE, steps_mult=2.0)),
                                        ("st", "STYLISED market (Phase 1 surface, H = 0.12)", S_st,
                                         stylised_strip)):
        r_h, r_r = run_market(label, S)
        ph, pr = r_h["params"], r_r["params"]
        rough_pricer = rh.RoughPricer()
        rep_h = by_tau(per_expiry_report(ph, S, heston_cf_factory))
        rep_r = by_tau(per_expiry_report(pr, S, lambda p, t: rh.cf_factory(p, t), pricer=rough_pricer))
        sk_m = skews(market_strip)
        sk_h = skews(heston_strip(ph))
        sk_r = skews(rough_strip(pr))
        results[key] = dict(label=label, S=S, r_h=r_h, r_r=r_r, rep_h=rep_h, rep_r=rep_r,
                            sk_m=sk_m, sk_h=sk_h, sk_r=sk_r,
                            sl_m=loglog_slope(sk_m), sl_h=loglog_slope(sk_h), sl_r=loglog_slope(sk_r),
                            loc={n: (local_slope(v, 1, 3), local_slope(v, 7, 14))
                                 for n, v in (("market", sk_m), ("Heston", sk_h), ("rough", sk_r))})

        R = results[key]
        print(f"\n  {'tau(d)':>7} {'Heston rmse':>12} {'rough rmse':>11}   (vol points)")
        for d in FIT_DAYS:
            a, b = rep_h.get(d), rep_r.get(d)
            print(f"  {d:7d} {fmt(a['rmse']*100 if a else None, '12.3f')} "
                  f"{fmt(b['rmse']*100 if b else None, '11.3f')}")
        print(f"\n  {'tau(d)':>7} {'market':>9} {'Heston':>9} {'rough':>9} {'H/mkt':>7} {'R/mkt':>7}")
        for d in SKEW_DAYS:
            m, h, r = sk_m.get(d), sk_h.get(d), sk_r.get(d)
            print(f"  {d:7d} {fmt(m)} {fmt(h)} {fmt(r)} "
                  f"{fmt(abs(h/m) if (m and h) else None, '7.3f')} {fmt(abs(r/m) if (m and r) else None, '7.3f')}")
        print(f"  short-end (<= {SHORT_END} d) log-log slope: market {R['sl_m']:+.3f}  "
              f"Heston {R['sl_h']:+.3f}  rough {R['sl_r']:+.3f}   (H - 1/2 = {H_TRUE-0.5:+.3f})",
              flush=True)
        print("  local slopes 1-3 d / 7-14 d: " + "  ".join(
            f"{n} {a:+.3f} / {b:+.3f}" for n, (a, b) in R["loc"].items()), flush=True)

    # --- figure: skew term structures for both markets + error by maturity --------
    plt.style.use("dark_background")
    fig, axes = plt.subplots(2, 2, figsize=(15, 9))
    fig.patch.set_facecolor("#0b0d0f")
    colours = {"m": "#00f2ff", "h": "#ffb020", "r": "#7ee787"}
    from matplotlib.ticker import NullFormatter, ScalarFormatter
    for col, key in enumerate(("in", "st")):
        R = results[key]
        ax = axes[0, col]
        for tag, sk, style, name, sl in (("m", R["sk_m"], "o-", "market", R["sl_m"]),
                                         ("h", R["sk_h"], "s--", "vanilla Heston", R["sl_h"]),
                                         ("r", R["sk_r"], "^-.", f"rough Heston (Ĥ={R['r_r']['params'].H:.3f})",
                                          R["sl_r"])):
            ds = np.array(sorted(sk))
            ax.loglog(ds, np.abs([sk[d] for d in ds]), style, color=colours[tag], ms=5, lw=1.5,
                      label=f"{name}   slope≤{SHORT_END}d {sl:+.2f}")
        ax.set_facecolor("#161b22")
        ax.set_xlabel("τ  (days)", color="#9aa4b2", fontsize=9)
        ax.set_ylabel("|∂σ/∂k|  at the money", color="#9aa4b2", fontsize=9)
        ax.set_title(f"{R['label']}\nATM skew term structure (H − ½ = {H_TRUE-0.5:+.2f})",
                     color="white", fontsize=10)
        ax.legend(fontsize=8, facecolor="#0b0d0f", edgecolor="#2d333b")
        for axis in (ax.xaxis, ax.yaxis):
            axis.set_major_formatter(ScalarFormatter())
            axis.set_minor_formatter(NullFormatter())

        ax = axes[1, col]
        xs = np.arange(len(FIT_DAYS))
        hv = [R["rep_h"][d]["rmse"] * 100 if d in R["rep_h"] else np.nan for d in FIT_DAYS]
        rv = [R["rep_r"][d]["rmse"] * 100 if d in R["rep_r"] else np.nan for d in FIT_DAYS]
        ax.bar(xs - 0.2, hv, width=0.4, color=colours["h"],
               label=f"Heston  ({R['r_h']['rmse_vol']*100:.2f} vp overall)")
        ax.bar(xs + 0.2, rv, width=0.4, color=colours["r"],
               label=f"rough Heston  ({R['r_r']['rmse_vol']*100:.2f} vp overall)")
        ax.set_xticks(xs)
        ax.set_xticklabels([str(d) for d in FIT_DAYS])
        ax.set_facecolor("#161b22")
        ax.set_xlabel("τ  (days)", color="#9aa4b2", fontsize=9)
        ax.set_ylabel("rmse  (vol points)", color="#9aa4b2", fontsize=9)
        ax.set_title("FIT ERROR BY MATURITY", color="white", fontsize=10)
        ax.legend(fontsize=8, facecolor="#0b0d0f", edgecolor="#2d333b")
    fig.subplots_adjust(left=0.06, right=0.98, top=0.92, bottom=0.07, hspace=0.38, wspace=0.18)
    out = OUT / "rough_vs_heston.png"
    fig.savefig(out, dpi=120, facecolor=fig.get_facecolor())
    print(f"\n  figure -> {out}")

    # --- record -------------------------------------------------------------------
    L = ["# Phase 2 — rough Heston vs vanilla Heston", "",
         "Both models fitted by the same Levenberg-Marquardt driver, in implied vol, "
         f"weighting **{WEIGHTING}** (see `study_h_identifiability.py` for why not vega²), "
         f"to {len(FIT_DAYS)} maturities from {FIT_DAYS[0]} to {FIT_DAYS[-1]} days × {N_K} strikes "
         "across ±3σ.", ""]
    for key in ("in", "st"):
        R = results[key]
        ph, pr = R["r_h"]["params"], R["r_r"]["params"]
        L += [f"## {R['label']}", "",
              "| model | " + " | ".join(rh.RoughHestonParams.NAMES) + " | rmse (vp) |",
              "|---|" + "---|" * (len(rh.RoughHestonParams.NAMES) + 1)]
        if key == "in":
            L.append("| **truth** | " + " | ".join(f"{getattr(TRUE, n):.4f}" for n in rh.RoughHestonParams.NAMES)
                     + " | — |")
        L.append("| vanilla Heston | " + " | ".join(f"{getattr(ph, n):.4f}" for n in HestonParams.NAMES)
                 + f" | — | {R['r_h']['rmse_vol']*100:.3f} |")
        L.append("| rough Heston | " + " | ".join(f"{getattr(pr, n):.4f}" for n in rh.RoughHestonParams.NAMES)
                 + f" | {R['r_r']['rmse_vol']*100:.3f} |")
        L += ["", f"Rough fit: {R['r_r']['iterations']} iterations, stopped on `{R['r_r']['reason']}`; "
                  f"pricer {R['r_r']['pricer_stats']}.", "",
              "| tau (days) | Heston rmse (vp) | rough rmse (vp) |", "|---|---|---|"]
        for d in FIT_DAYS:
            a, b = R["rep_h"].get(d), R["rep_r"].get(d)
            L.append(f"| {d} | {a['rmse']*100:.3f} | " if a else f"| {d} | — | ")
            L[-1] += f"{b['rmse']*100:.3f} |" if b else "— |"
        L += ["", "| tau (days) | market skew | Heston | rough Heston | Heston / market | rough / market |",
              "|---|---|---|---|---|---|"]
        for d in SKEW_DAYS:
            m, h, r = R["sk_m"].get(d), R["sk_h"].get(d), R["sk_r"].get(d)
            cell = lambda v: f"{v:.4f}" if v is not None else "—"
            ratio = lambda a, b: f"{abs(a/b):.3f}" if (a is not None and b) else "—"
            L.append(f"| {d} | {cell(m)} | {cell(h)} | {cell(r)} | {ratio(h, m)} | {ratio(r, m)} |")
        L += ["", f"Log-log slope of |skew| against tau over 1–{SHORT_END} days: "
                  f"market **{R['sl_m']:+.3f}**, Heston **{R['sl_h']:+.3f}**, rough Heston "
                  f"**{R['sl_r']:+.3f}**; planted H − ½ = {H_TRUE-0.5:+.3f}.", "",
              "| local slope | market | Heston | rough Heston |", "|---|---|---|---|",
              "| 1–3 days | " + " | ".join(f"{R['loc'][n][0]:+.3f}" for n in ("market", "Heston", "rough")) + " |",
              "| 7–14 days | " + " | ".join(f"{R['loc'][n][1]:+.3f}" for n in ("market", "Heston", "rough")) + " |",
              ""]
    DOC.write_text("\n".join(L) + "\n", encoding="utf-8")
    print(f"  record -> {DOC}")


if __name__ == "__main__":
    main()
