"""
Session E: calibrating the lifted rough Heston, and the comparison that
justifies Phase 2.

Kept separate from test_calibrate.py because a rough objective evaluation is
a tenth of a second per maturity, not milliseconds; this suite runs in minutes.

E1  plant-and-recover on (v0, kappa, theta, xi, rho, H) with the SAME
    Levenberg-Marquardt driver that fits vanilla Heston.
E1  identifiability of H, MEASURED: the Gauss-Newton standard error of H for
    the surface actually used, and fits under noise checked against it. The
    first version of this test asserted H to +/-0.03 on a vega^2-weighted
    20-quote surface; the standard error there is 0.20, so that assertion was
    never true -- three seeds gave H = 0.50, 0.25, 0.12 and in all three the
    optimiser had found a LOWER cost than the truth.
E2  fit both models to a market generated by rough Heston: the rough model's
    short-end ATM skew slope must follow the market's, vanilla Heston's must
    flatten. Compared with the market's MEASURED slope, not with H - 1/2: at
    xi = 0.5 the rough model's own 1-14 day slope is -0.47, not -0.38 -- a
    higher-order vol-of-vol effect that shrinks as xi -> 0 (-0.42 at xi = 0.05).

    python test_rough_calibration.py
"""

import math
import sys
import time

import numpy as np

import volsurf_core as vc
import pricing.fourier as fo
import models.rough_heston as rh
from models.heston import HestonParams
from calibrate.objective import MarketSurface
from calibrate.fit import (DEFAULT_STARTS, ROUGH_TRANSFORM, calibrate_heston,
                           calibrate_rough_heston)


PASS, FAIL = [], []


def check(name, cond, detail=""):
    (PASS if cond else FAIL).append(name)
    print(f"  [{'PASS' if cond else 'FAIL'}] {name}" + (f"  -- {detail}" if detail else ""))


np.seterr(all="ignore")
TRUE = rh.RoughHestonParams(0.04, 2.0, 0.045, 0.5, -0.7, 0.12)
START = rh.RoughHestonParams(0.05, 1.5, 0.06, 0.7, -0.5, 0.25)
TAUS = np.array([2, 14, 90, 365]) / 365.0


def build_surface(taus, n_k=5, params=TRUE, noise=0.0, seed=0):
    """A synthetic market generated by the lifted model itself."""
    rng = np.random.default_rng(seed)
    T, K, V, W = [], [], [], []
    for tau in taus:
        band = 3.0 * math.sqrt(params.v0) * math.sqrt(tau)
        ks = np.linspace(-band, band, n_k)
        c, _ = rh.call_prices(ks, tau, params, tol=1e-10, steps_mult=2.0)
        iv = fo.implied_vols_from_calls(c, ks, tau)
        for k, v in zip(ks, iv):
            if not np.isfinite(v):
                continue
            vv = v + rng.normal(0.0, noise)
            T.append(tau)
            K.append(k)
            V.append(vv)
            W.append(float(vc.quote_weight(0.005, vc.bs_vega(1.0, math.exp(k), max(vv, 0.01), tau))))
    return MarketSurface(np.array(T), np.array(K), np.array(V), np.array(W))


# --- E1 ------------------------------------------------------------------------
def test_plant_and_recover():
    print("\nE1 -- plant and recover, clean data, from a start 25-100% off in every parameter")
    S = build_surface(TAUS)
    t0 = time.perf_counter()
    res = calibrate_rough_heston(S, starts=(START,), max_iter=60, max_seconds=600)
    dt = time.perf_counter() - t0
    p = res["params"]
    errs = {n: abs(getattr(p, n) - getattr(TRUE, n)) / abs(getattr(TRUE, n))
            for n in ROUGH_TRANSFORM.names}
    worst = max(errs, key=errs.get)
    print("      " + "  ".join(f"{n}={getattr(p, n):.5f}" for n in ROUGH_TRANSFORM.names)
          + f"   ({dt:.0f}s, {res['iterations']} iters, {res['n_fev']} evals, {res['reason']})")
    check("every parameter recovered to better than 0.1%", max(errs.values()) < 1e-3,
          f"worst {worst} at {errs[worst]*100:.4f}%")
    check("H recovered to +/-0.02 (the plan's bar) -- and in fact to 1e-4",
          abs(p.H - TRUE.H) < 1e-4, f"H = {p.H:.6f} vs {TRUE.H}")
    check("rmse under 0.001 vol points", res["rmse_vol"] < 1e-5,
          f"{res['rmse_vol']*100:.6f} vol points")
    check("the same driver: result carries the generic fields",
          all(k in res for k in ("iterations", "n_fev", "reason", "cost_spread", "prior_cost")))
    check("reports the lift's kernel error at the fitted H and the pricer's work",
          "kernel_error" in res and res["kernel_error"] < 0.012 and res["pricer_stats"]["solves"] > 0,
          f"kernel error {res['kernel_error']:.3%}, {res['pricer_stats']}")
    check("fitted parameters are inside their domain", p.valid())


def test_h_identifiability():
    print("\nE1 -- identifiability of H: the standard error first, then fits checked against it")
    import study_h_identifiability as study
    from calibrate.objective import residuals

    rows = study.quotes((2, 14, 90, 365), 5)
    t0 = time.perf_counter()
    iv, J = study.jacobian(rows)
    vega = np.array([float(vc.bs_vega(1.0, math.exp(k), v, t)) for (t, k), v in zip(rows, iv)])
    homo = np.full(len(rows), 0.005 ** 2)
    names = rh.RoughHestonParams.NAMES
    jH, jxi = names.index("H"), names.index("xi")

    w_v = (vega / 0.005) ** 2
    cov_v = study.covariance(J, w_v, homo)
    cov_e = study.covariance(J, np.ones(len(rows)), homo)
    se_v, se_e = math.sqrt(cov_v[jH, jH]), math.sqrt(cov_e[jH, jH])
    corr = cov_e[jH, jxi] / math.sqrt(cov_e[jH, jH] * cov_e[jxi, jxi])
    eff = float(w_v.sum() ** 2 / (w_v ** 2).sum())
    print(f"      SE(H): vega^2 weights {se_v:.3f}, equal weights {se_e:.3f};  corr(H, xi) {corr:+.2f};"
          f"  effective quotes under vega^2 {eff:.1f}/{len(rows)}  ({time.perf_counter()-t0:.0f}s)")
    check("under vega^2 weights H is NOT identified from this surface: SE(H) > 0.15",
          se_v > 0.15, f"SE(H) = {se_v:.3f} -- the old +/-0.03 assertion was never attainable")
    check("...because the weights leave fewer than 3 effective quotes",
          eff < 3.0, f"{eff:.1f} of {len(rows)}")
    check("equal weights in vol make H identifiable at this noise: SE(H) < 0.06", se_e < 0.06,
          f"SE(H) = {se_e:.3f}")
    check("H and xi trade off almost perfectly (|corr| > 0.9) -- the rough analogue of kappa/theta",
          abs(corr) > 0.9, f"corr = {corr:+.3f}")

    noise = 0.005
    t0 = time.perf_counter()
    for seed in range(3):
        Sn = build_surface(TAUS, noise=noise, seed=seed)
        Sn = MarketSurface(Sn.tau, Sn.k, Sn.iv, np.ones(len(Sn)))
        res = calibrate_rough_heston(Sn, starts=(START,), max_iter=40, max_seconds=400)
        p = res["params"]
        pricer = rh.RoughPricer()
        fac = lambda q, t: rh.cf_factory(q, t)
        c_true = float(np.sum(residuals(TRUE, Sn, fac, pricer=pricer)[0] ** 2))
        check(f"seed {seed}: fitted H within 3 SE of the truth",
              abs(p.H - TRUE.H) < 3.0 * se_e,
              f"H = {p.H:.4f} (|dH| = {abs(p.H-TRUE.H):.3f} vs 3 SE = {3*se_e:.3f}); "
              f"rmse {res['rmse_vol']*100:.3f} vp; {res['iterations']} it")
        check(f"seed {seed}: the optimiser reaches at least the truth's cost",
              res["cost"] <= c_true * (1.0 + 1e-6), f"fit {res['cost']:.4e} vs truth {c_true:.4e}")
    print(f"      ({time.perf_counter()-t0:.0f}s for 3 fits)")


# --- E2 ------------------------------------------------------------------------
E2_DAYS = (1, 3, 7, 14, 60, 365)
SKEW_DAYS = (1, 2, 3, 5, 7, 10, 14)


def test_skew_term_structure():
    print("\nE2 -- both models on a market generated by rough Heston (H = 0.12)")
    import capture_rough_vs_heston as cap

    S = cap.surface_from(cap.rough_strip(TRUE, steps_mult=2.0), days=E2_DAYS, n_k=5)
    print(f"      market: {len(S)} quotes, {S.n_expiries} expiries, equal weights")
    t0 = time.perf_counter()
    r_h = calibrate_heston(S, starts=DEFAULT_STARTS[:2], max_iter=60, max_seconds=120)
    ph = r_h["params"]
    print(f"      Heston: rmse {r_h['rmse_vol']*100:.3f} vp ({time.perf_counter()-t0:.0f}s)  "
          + "  ".join(f"{n}={getattr(ph, n):.4f}" for n in HestonParams.NAMES))
    t0 = time.perf_counter()
    r_r = calibrate_rough_heston(S, starts=(START,), max_iter=60, max_seconds=900)
    pr = r_r["params"]
    print(f"      rough : rmse {r_r['rmse_vol']*100:.4f} vp ({time.perf_counter()-t0:.0f}s, "
          f"{r_r['iterations']} it, {r_r['reason']})  "
          + "  ".join(f"{n}={getattr(pr, n):.4f}" for n in rh.RoughHestonParams.NAMES))

    sk = {"market": cap.skews(cap.rough_strip(TRUE, steps_mult=2.0), days=SKEW_DAYS),
          "Heston": cap.skews(cap.heston_strip(ph), days=SKEW_DAYS),
          "rough": cap.skews(cap.rough_strip(pr), days=SKEW_DAYS)}
    sl = {k: cap.loglog_slope(v) for k, v in sk.items()}
    print(f"      {'tau(d)':>7} {'market':>9} {'Heston':>9} {'rough':>9}")
    for d in SKEW_DAYS:
        print(f"      {d:7d} " + " ".join(f"{sk[k].get(d, float('nan')):9.4f}" for k in sk))
    print(f"      short-end slope: market {sl['market']:+.3f}  Heston {sl['Heston']:+.3f}  "
          f"rough {sl['rough']:+.3f}")

    def local(sk, a, b):
        return math.log(abs(sk[b] / sk[a])) / math.log(b / a)

    loc = {k: (local(v, 1, 3), local(v, 7, 14)) for k, v in sk.items()}
    print("      local slopes (1-3 d, 7-14 d): " +
          "  ".join(f"{k} {a:+.3f} / {b:+.3f}" for k, (a, b) in loc.items()))

    check("every maturity priced for all three curves (no gaps to hide)",
          all(len(v) == len(SKEW_DAYS) for v in sk.values()),
          ", ".join(f"{k} {len(v)}" for k, v in sk.items()))
    check("rough Heston recovers the planted H to 0.02", abs(pr.H - TRUE.H) < 0.02, f"H = {pr.H:.4f}")
    check("rough Heston fits its own market to under 0.05 vol points", r_r["rmse_vol"] < 5e-4,
          f"{r_r['rmse_vol']*100:.4f} vp")
    check("rough Heston's 1-14 day skew slope matches the market's to 0.05",
          abs(sl["rough"] - sl["market"]) < 0.05, f"{sl['rough']:+.3f} vs {sl['market']:+.3f}")
    # The structural statement. A diffusion's ATM skew tends to a constant as
    # tau -> 0, so its log-log slope goes to zero at the SHORT end. Fitted
    # Heston can still copy the market over a week or two -- here it pushes
    # kappa towards 1/(10 days) so that its transition from flat to decaying
    # sits inside the window -- but it cannot follow below that. The slope over
    # the whole 1-14 day window hides this (measured -0.32 vs -0.47 on the
    # capture's surface); the bend does not.
    check("at 1-3 days vanilla Heston is flatter than the market by more than 0.2",
          loc["Heston"][0] - loc["market"][0] > 0.2,
          f"{loc['Heston'][0]:+.3f} vs {loc['market'][0]:+.3f}")
    check("...and rough Heston is not: within 0.05 of the market there",
          abs(loc["rough"][0] - loc["market"][0]) < 0.05,
          f"{loc['rough'][0]:+.3f} vs {loc['market'][0]:+.3f}")
    bend = {k: b - a for k, (a, b) in loc.items()}
    check("vanilla Heston's log-log skew curve BENDS (7-14 d slope minus 1-3 d slope < -0.2)",
          bend["Heston"] < -0.2, f"bend {bend['Heston']:+.3f}")
    check("...rough Heston's bends exactly as the market's does (to 0.05)",
          abs(bend["rough"] - bend["market"]) < 0.05,
          f"rough {bend['rough']:+.3f}, market {bend['market']:+.3f}")
    one_r = abs(sk["rough"][1] / sk["market"][1])
    one_h = abs(sk["Heston"][1] / sk["market"][1])
    check("rough Heston delivers the market's one-day skew to within 10%", 0.9 < one_r < 1.1,
          f"{one_r:.1%}")
    check("vanilla Heston falls short of it by more than 15%", one_h < 0.85,
          f"{one_h:.1%} (Phase 1's 58% was an artefact of vega^2 weights, see phase1_baseline.md)")
    check("rough Heston's fit error is under a fifth of vanilla Heston's",
          r_r["rmse_vol"] < 0.2 * r_h["rmse_vol"],
          f"{r_r['rmse_vol']*100:.3f} vs {r_h['rmse_vol']*100:.3f} vol points")


# --- Session G: weighting for H --------------------------------------------------
def test_weighting_for_h():
    """
    The analytics review asked for inverse-variance or hybrid weights that anchor
    the short-end skew. Mechanics first (the anchor IS the local skew estimator,
    rows are appended correctly, failures reach the anchors), then the study's
    conclusions, asserted on its numbers.
    """
    print("\nG -- calibration weights for H: vega^2, inverse variance, hybrid skew anchors")
    import calibrate.weights as wt
    import study_h_weighting as shw
    from calibrate.objective import residuals

    F, tau, s_atm = 1.0, 7 / 365, 0.16
    ks = np.linspace(-2.5, 2.5, 21) * s_atm * math.sqrt(tau)
    zs = ks / (s_atm * math.sqrt(tau))
    ivs = s_atm - 1.1 * ks + 5.0 * ks ** 2 - 30.0 * ks ** 3
    qw = 1.0 / (0.002 + 0.001 * np.abs(zs)) ** 2
    a, _ = wt.skew_functional(ks, zs, qw, window=1.5)
    ref, _, _ = vc.atm_skew_from_slice(ks, ivs, zs=zs, weights=qw, window=1.5)
    check("the anchor's linear functional reproduces atm_skew_from_slice exactly",
          abs(float(a @ ivs) - ref) < 1e-10, f"{float(a @ ivs):.12f} vs {ref:.12f}")

    tau_v = np.repeat([2 / 365, 30 / 365, 1.0], 7)
    w = np.r_[np.full(7, 1.0), np.full(7, 5.0), np.full(7, 50.0)]
    wb = wt.balance_by_expiry(tau_v, w)
    sums = [wb[tau_v == t].sum() for t in np.unique(tau_v)]
    check("balance_by_expiry: equal total per expiry, grand total kept",
          np.allclose(sums, sums[0]) and abs(wb.sum() - w.sum()) < 1e-9, f"{np.round(sums, 3)}")

    S = build_surface(np.array([2, 14, 90]) / 365.0, n_k=7)
    sd = np.full(len(S), 0.005)
    anchors = wt.build_anchors(S.tau, S.k, S.iv, sd, window=3.5)
    SA = MarketSurface(S.tau, S.k, S.iv, np.ones(len(S)), anchors=anchors)
    fac = lambda q, t: rh.cf_factory(q, t)
    pricer = rh.RoughPricer()
    r_true, _ = residuals(TRUE, SA, fac, pricer=pricer)
    q_noise = float(np.max(np.abs(r_true[:len(S)])))
    check("anchor rows are appended (one per expiry <= 30 d) and are pricing noise at the generating parameters",
          len(r_true) == len(S) + 2 and float(np.max(np.abs(r_true[len(S):]))) < 1e-2,
          f"{len(anchors)} anchors, max anchor residual {float(np.max(np.abs(r_true[len(S):]))):.1e} "
          f"(quote rows {q_noise:.1e}: the market was priced with a different quadrature)")
    wrong = rh.RoughHestonParams(0.04, 2.0, 0.045, 0.5, -0.7, 0.30)
    r_w, _ = residuals(wrong, SA, fac, pricer=pricer)
    mv = S.iv + r_w[:len(S)]
    manual = [math.sqrt(an.weight) * (float(an.a @ mv[an.idx]) - an.target) / an.se for an in anchors]
    check("an anchor residual is sqrt(weight) (model skew - market skew) / SE, recomputed by hand",
          np.allclose(r_w[len(S):], manual, atol=1e-10) and abs(r_w[len(S)]) > 1.0,
          f"H = 0.30 gives short-end anchor residuals {np.round(r_w[len(S):], 2)}")

    out = shw.run(verbose=False)
    design, spread = "recorder surface, 10 expiries x 9", "spread-based noise (tick + 2.5% of value)"
    homo = "homoscedastic 0.5 vp noise"
    g = lambda sc, nz=spread: out[(design, nz, sc)]
    rms = lambda a_, key: math.hypot(a_["se_H"], a_[key])
    print("      recorder surface, spread noise, RMS error in H [long end wrong / short end wrong]: " + "  ".join(
        f"{sc}: {rms(g(sc), 'bias_H'):.3f}/{rms(g(sc), 'bias_H_short'):.3f}"
        for sc in ("vega2", "inverse_variance", "hybrid", "hybrid x25")))
    check("inverse variance cuts SE(H) at least 4x against vega^2 (both noise models)",
          g("inverse_variance")["se_H"] < g("vega2")["se_H"] / 4
          and g("inverse_variance", homo)["se_H"] < g("vega2", homo)["se_H"] / 4,
          f"{g('vega2')['se_H']:.4f} -> {g('inverse_variance')['se_H']:.4f} (spread); "
          f"{g('vega2', homo)['se_H']:.4f} -> {g('inverse_variance', homo)['se_H']:.4f} (0.5 vp)")
    corrs = [abs(v["corr_H_xi"]) for v in out.values()]
    check("corr(H, xi) > 0.9 under EVERY scheme and design: re-weighting cannot remove it",
          min(corrs) > 0.9, f"min |corr| {min(corrs):.3f} over {len(corrs)} cases")
    worst = {sc: max(rms(g(sc), "bias_H"), rms(g(sc), "bias_H_short")) for sc in ("vega2", "inverse_variance", "hybrid x25")}
    check("skew-anchored hybrid has the best worst case over the two misspecifications",
          worst["hybrid x25"] < worst["inverse_variance"] and worst["hybrid x25"] < worst["vega2"],
          ", ".join(f"{k}: {v:.3f}" for k, v in worst.items()))
    check("...but inverse variance wins when only the long end is wrong: anchors cost precision",
          rms(g("inverse_variance"), "bias_H") < rms(g("hybrid x25"), "bias_H"))


if __name__ == "__main__":
    print("=" * 74)
    print("Session E -- rough Heston calibration and the skew comparison")
    print("=" * 74)
    t0 = time.perf_counter()
    test_plant_and_recover()
    test_h_identifiability()
    test_skew_term_structure()
    test_weighting_for_h()
    print("\n" + "=" * 74)
    print(f"{len(PASS)} passed, {len(FAIL)} failed   ({time.perf_counter()-t0:.0f}s)")
    for f in FAIL:
        print(f"  FAILED: {f}")
    print("=" * 74)
    sys.exit(1 if FAIL else 0)
