"""
Session C: the calibration objective and the Levenberg-Marquardt driver.

The tests that matter most are the identifiability ones at the end. On clean data
every parameter comes back exactly, which proves the machinery works and almost
nothing else. Under realistic quote noise the SURFACE is still recovered to the
noise level while kappa and theta are not recovered at all -- and that is a
property of the problem, not a bug in the fit. Asserting the parameters instead
would have been asserting something untrue.

    python test_calibrate.py
"""

import math
import sys
import time

import numpy as np

import volsurf_core as vc
import pricing.fourier as fo
from models.heston import HestonParams, char_func
from calibrate.objective import (MarketSurface, loss, per_expiry_report,
                                 residuals, rmse_vol)
from calibrate.fit import (DEFAULT_STARTS, HESTON_TRANSFORM, calibrate_heston,
                           heston_cf_factory, levenberg_marquardt)


PASS, FAIL = [], []


def check(name, cond, detail=""):
    (PASS if cond else FAIL).append(name)
    print(f"  [{'PASS' if cond else 'FAIL'}] {name}" + (f"  -- {detail}" if detail else ""))


TRUE = HestonParams(v0=0.040, kappa=2.00, theta=0.045, xi=0.50, rho=-0.70)


def build_surface(taus, n_k=7, noise=0.0, seed=0, params=TRUE):
    """A synthetic market generated by `params`, optionally with quote noise."""
    rng = np.random.default_rng(seed)
    T, K, V, W = [], [], [], []
    for tau in taus:
        band = 3.0 * math.sqrt(params.v0) * math.sqrt(tau)
        ks = np.linspace(-band, band, n_k)
        vs = fo.smile(ks, tau, lambda u, t=tau: char_func(u, t, params))
        for k, v in zip(ks, vs):
            if v is None:
                continue
            vv = v + rng.normal(0.0, noise)
            T.append(tau)
            K.append(k)
            V.append(vv)
            W.append(float(vc.quote_weight(
                0.005, vc.bs_vega(1.0, math.exp(k), max(vv, 0.01), tau))))
    return MarketSurface(np.array(T), np.array(K), np.array(V), np.array(W))


FAST_TAUS = np.array([7, 60, 365]) / 365.0


# --- the Levenberg-Marquardt driver itself ----------------------------------
def test_lm_driver():
    print("\nC2 -- Levenberg-Marquardt on problems with known answers")

    # Linear least squares: LM must land exactly on the normal-equation solution
    rng = np.random.default_rng(0)
    A = rng.normal(size=(40, 3))
    b = rng.normal(size=40)
    exact = np.linalg.lstsq(A, b, rcond=None)[0]
    x, cost, info = levenberg_marquardt(lambda z: A @ z - b, np.zeros(3))
    check("linear least squares matches the normal equations",
          float(np.max(np.abs(x - exact))) < 1e-9,
          f"max dev {float(np.max(np.abs(x - exact))):.2e} in {info['iterations']} iters")

    # Nonlinear: y = a exp(b x), recovered from noiseless data
    xs = np.linspace(0.0, 2.0, 30)
    a_t, b_t = 2.5, -0.8
    ys = a_t * np.exp(b_t * xs)
    x2, c2, i2 = levenberg_marquardt(
        lambda p: p[0] * np.exp(p[1] * xs) - ys, np.array([1.0, -0.1]))
    check("nonlinear exponential fit recovers (a, b)",
          abs(x2[0] - a_t) < 1e-6 and abs(x2[1] - b_t) < 1e-6,
          f"a={x2[0]:.8f} b={x2[1]:.8f} in {i2['iterations']} iters")

    # It must stop, and say why
    check("reports a termination reason",
          info['reason'] in ('ftol', 'xtol', 'gradient', 'no_descent', 'max_iter'),
          info['reason'])
    check("cost decreases monotonically", cost <= float(b @ b) + 1e-12)

    # A flat problem must not spin forever
    _, _, i3 = levenberg_marquardt(lambda p: np.zeros(5), np.ones(2), max_iter=50)
    check("a zero-residual problem terminates immediately",
          i3['iterations'] <= 2, f"{i3['iterations']} iterations, {i3['reason']}")


def test_transform():
    print("\nC2 -- parameter transform")
    x = HESTON_TRANSFORM.to_x(TRUE)
    back = HESTON_TRANSFORM.from_x(x)
    check("round-trips exactly",
          all(abs(getattr(back, n) - getattr(TRUE, n)) < 1e-12
              for n in HestonParams.NAMES))

    # Bounds cannot be violated whatever the optimiser does. This caught a real
    # bug: math.tanh(40) is EXACTLY 1.0 in float64, so an unscaled tanh map hands
    # the model rho = 1, where sqrt(1 - rho^2) = 0 and the simulator degenerates.
    for xr in (40.0, 1e3, -1e6):
        wild = HESTON_TRANSFORM.from_x(np.array([-40.0, 40.0, -40.0, 40.0, xr]))
        check(f"|rho| stays below 1 at x_rho = {xr:g}",
              abs(wild.rho) < 1.0, f"rho = {wild.rho:.10f}")
    wild = HESTON_TRANSFORM.from_x(np.array([-40.0, 40.0, -40.0, 40.0, 40.0]))
    check("extreme coordinates still give a valid parameter set",
          wild.valid(), f"v0={wild.v0:.2e}, rho={wild.rho:.6f}")

    # math.exp overflows above ~709, and LM genuinely reaches there when asked to
    # fit a shape the model cannot make. Caught by capture_calibration.py
    # crashing on a rough surface.
    for xp in (700.0, 1e4, 1e9, -1e9):
        try:
            q = HESTON_TRANSFORM.from_x(np.array([xp, xp, xp, xp, 0.0]))
            ok = q.valid() and all(math.isfinite(getattr(q, n))
                                   for n in HestonParams.NAMES)
        except OverflowError:
            ok = False
        check(f"log-parameters at x = {xp:g} do not overflow", ok)

    # And the cap must not cost accuracy on ordinary values
    for r in (-0.95, -0.7, 0.0, 0.5, 0.99):
        p = HestonParams(0.04, 2.0, 0.045, 0.5, r)
        back = HESTON_TRANSFORM.from_x(HESTON_TRANSFORM.to_x(p)).rho
        check(f"rho={r} round-trips through the cap", abs(back - r) < 1e-12,
              f"{back:.15f}")


# --- C1: the objective -------------------------------------------------------
def test_objective():
    print("\nC1 -- the objective")
    S = build_surface(FAST_TAUS)
    check("surface groups by expiry once", S.n_expiries == len(FAST_TAUS),
          f"{len(S)} quotes, {S.n_expiries} expiries")

    l0 = loss(TRUE, S, heston_cf_factory)
    check("loss is ~0 at the generating parameters", l0 < 1e-18, f"{l0:.2e}")
    check("rmse is ~0 vol points there",
          rmse_vol(TRUE, S, heston_cf_factory) < 1e-9)

    # Perturbing any single parameter must raise the loss, monotonically
    for name in HestonParams.NAMES:
        vals = []
        for f in (1.02, 1.05, 1.10):
            kw = {n: getattr(TRUE, n) for n in HestonParams.NAMES}
            kw[name] = kw[name] * f if name != 'rho' else kw[name] * (2.0 - f)
            vals.append(loss(HestonParams(**kw), S, heston_cf_factory))
        check(f"loss rises monotonically when {name} is perturbed",
              vals[0] > l0 and vals[1] > vals[0] and vals[2] > vals[1],
              " < ".join(f"{v:.2e}" for v in vals))

    # An unpriceable quote contributes zero rather than a fabricated residual
    S2 = MarketSurface(np.array([0.25, 0.25]), np.array([0.0, 25.0]),
                       np.array([0.20, 0.20]), np.array([1.0, 1.0]))
    r, failed = residuals(TRUE, S2, heston_cf_factory)
    check("a quote the model cannot price contributes exactly 0",
          failed >= 1 and r[1] == 0.0, f"{failed} unpriceable, r[1]={r[1]}")
    check("...and the residual vector keeps its length", len(r) == 2)

    rep = per_expiry_report(TRUE, S, heston_cf_factory)
    check("per-expiry report covers every expiry", len(rep) == len(FAST_TAUS))
    check("per-expiry rmse is ~0 at the truth",
          max(row['rmse'] for row in rep) < 1e-9)


# --- C2: plant and recover ---------------------------------------------------
def test_clean_recovery():
    print("\nC2 -- plant and recover, clean data")
    S = build_surface(FAST_TAUS)
    t0 = time.perf_counter()
    res = calibrate_heston(S, starts=DEFAULT_STARTS[:1])
    dt = time.perf_counter() - t0
    p = res['params']

    errs = {n: abs(getattr(p, n) - getattr(TRUE, n)) / abs(getattr(TRUE, n))
            for n in HestonParams.NAMES}
    worst = max(errs, key=errs.get)
    check("every parameter recovered to better than 1%",
          max(errs.values()) < 0.01,
          f"worst {worst} at {errs[worst]*100:.4f}%  ({dt:.1f}s, "
          f"{res['iterations']} iters)")
    check("rmse under 0.001 vol points", res['rmse_vol'] < 1e-5,
          f"{res['rmse_vol']*100:.6f} vol points")
    check("reports iterations, evaluations and why it stopped",
          all(k in res for k in ('iterations', 'n_fev', 'reason')),
          f"{res['iterations']} iters, {res['n_fev']} fevals, {res['reason']}")

    check("Feller is reported, not enforced",
          'feller' in res and 'feller_margin' in res,
          f"2*k*th - xi^2 = {res['feller_margin']:.4f} -> {res['feller']}")

    # The result must be a valid parameter set no matter what
    check("fitted parameters are inside their domain", p.valid())


def test_multistart():
    print("\nC2 -- multi-start")
    S = build_surface(FAST_TAUS)
    res = calibrate_heston(S, starts=DEFAULT_STARTS)
    check("runs every start and keeps the best",
          len(res['trials']) == len(DEFAULT_STARTS)
          and res['cost'] <= min(t['cost'] for t in res['trials']) + 1e-30,
          f"{len(res['trials'])} starts, best cost {res['cost']:.2e}")
    check("reports how much the answer depended on the start",
          res['cost_spread'] >= 1.0, f"cost spread {res['cost_spread']:.2f}x")
    check("all starts reach the same basin on clean data",
          res['cost_spread'] < 100.0,
          f"{res['cost_spread']:.2f}x -- clean data is not multi-modal here")


# --- C3: what is actually identifiable ---------------------------------------
def test_identifiability():
    """
    The honest test. Under realistic quote noise the surface fits beautifully and
    kappa and theta are still not determined. Asserting 5% parameter recovery --
    as the plan originally did -- would have been asserting something false.
    """
    print("\nC3 -- identifiability under 0.5 vol point quote noise")
    noise = 0.005
    fits = [calibrate_heston(build_surface(FAST_TAUS, noise=noise, seed=s),
                             starts=DEFAULT_STARTS[:1])
            for s in range(4)]
    P = [f['params'] for f in fits]

    rmses = [f['rmse_vol'] for f in fits]
    check("the SURFACE is still recovered, to about the noise level",
          max(rmses) < 3.0 * noise,
          f"rmse {min(rmses)*100:.3f}-{max(rmses)*100:.3f} vol points "
          f"vs {noise*100:.1f} injected")

    def spread(name):
        v = np.array([getattr(p, name) for p in P])
        return float(np.std(v) / abs(np.mean(v)))

    sp = {n: spread(n) for n in HestonParams.NAMES}
    print("      spread across noise seeds: " +
          "  ".join(f"{n}={sp[n]*100:.1f}%" for n in HestonParams.NAMES))

    check("v0 is well determined (the short end pins it)",
          sp['v0'] < 0.10, f"{sp['v0']*100:.1f}%")
    check("rho is well determined (the skew pins it)",
          sp['rho'] < 0.15, f"{sp['rho']*100:.1f}%")
    check("kappa is NOT determined, and that is the problem not the fit",
          sp['kappa'] > 0.20,
          f"{sp['kappa']*100:.1f}% -- kappa and xi trade off against each other")


def test_identifiability_mechanism():
    """
    Prove the diagnosis rather than assert it: if kappa and theta are loose
    because the surface does not extend past the relaxation time 1/kappa, then
    adding longer maturities must tighten them.
    """
    print("\nC3 -- the mechanism: maturity range vs 1/kappa")
    short = np.array([7, 30, 90, 365]) / 365.0
    long_ = np.array([7, 30, 90, 365, 730, 1095]) / 365.0
    print(f"      1/kappa = {1/TRUE.kappa:.2f} y; short surface reaches "
          f"{short.max():.2f} y, long reaches {long_.max():.2f} y")

    def spreads(taus):
        P = [calibrate_heston(build_surface(taus, noise=0.005, seed=s),
                              starts=DEFAULT_STARTS[:1])['params']
             for s in range(4)]
        out = {}
        for n in HestonParams.NAMES:
            v = np.array([getattr(p, n) for p in P])
            out[n] = float(np.std(v) / abs(np.mean(v)))
        return out

    a, b = spreads(short), spreads(long_)
    for label, d in (("to 1 year ", a), ("to 3 years", b)):
        print(f"      {label}: " +
              "  ".join(f"{n}={d[n]*100:5.1f}%" for n in HestonParams.NAMES))

    check("extending past 1/kappa tightens theta substantially",
          b['theta'] < 0.5 * a['theta'],
          f"{a['theta']*100:.1f}% -> {b['theta']*100:.1f}%")
    check("...and tightens kappa too",
          b['kappa'] < a['kappa'],
          f"{a['kappa']*100:.1f}% -> {b['kappa']*100:.1f}%")
    check("so the looseness is the maturity range, not the optimiser",
          b['theta'] < 0.15,
          "a long-run level cannot be read off a surface that stops before "
          "the process has relaxed")


def test_failure_is_never_cheaper():
    """
    The objective's handling of quotes the model cannot price. A rough Heston
    calibration exploited the old convention (every unpriceable quote
    contributed zero): it walked to parameters where two whole maturities
    failed and the cost FELL. A model failure must cost at least as much as the
    worst priceable outcome.
    """
    print("\nC1 -- a quote the model fails on is charged, never zeroed")
    from calibrate.objective import FAILURE_IV, MODEL_FAILURE, BELOW_RESOLUTION, model_ivs

    S = build_surface(FAST_TAUS)
    good, _ = residuals(TRUE, S, heston_cf_factory)

    def broken_pricer(ks, tau, cf, tol=None):
        out = np.atleast_1d(fo.carr_madan_call(ks, tau, cf, tol=tol))
        if abs(tau - FAST_TAUS[1]) < 1e-12:
            return np.full_like(out, 1.9e18)          # what the runaway returned
        return out

    r, failed = residuals(TRUE, S, heston_cf_factory, pricer=broken_pricer)
    idx = S.by_expiry[1][1]
    check("a broken maturity is counted as failed", failed == len(idx), f"{failed} of {len(S)}")
    check("...and is charged at the inversion ceiling, not zero",
          np.allclose(r[idx], np.sqrt(S.weight[idx]) * (FAILURE_IV - S.iv[idx])),
          f"min charge {float(np.min(np.abs(r[idx]))):.3f}")
    check("failing makes the cost HIGHER than fitting exactly", float(r @ r) > float(good @ good) + 1.0,
          f"{float(r @ r):.2e} vs {float(good @ good):.2e}")
    worst_priceable = np.sqrt(S.weight[idx]) * np.maximum(FAILURE_IV - S.iv[idx], S.iv[idx] - 1e-4)
    check("the charge is at least the worst priceable miss for every quote",
          np.all(np.abs(r[idx]) >= worst_priceable - 1e-12))

    _, _, status = model_ivs(TRUE, S, heston_cf_factory, pricer=broken_pricer, return_status=True)
    check("status marks the broken strip MODEL_FAILURE and the rest OK",
          np.all(status[idx] == MODEL_FAILURE) and np.all(np.delete(status, idx) == 0))

    # A deep quote where BOTH the market and the model are below resolution:
    # genuinely no information, still zero (the original, correct, case).
    S2 = MarketSurface(np.array([0.25]), np.array([25.0]), np.array([0.20]), np.array([1.0]))
    r2, f2 = residuals(TRUE, S2, heston_cf_factory)
    _, _, st2 = model_ivs(TRUE, S2, heston_cf_factory, return_status=True)
    check("market and model both below resolution -> no information -> 0",
          f2 == 1 and r2[0] == 0.0 and st2[0] == BELOW_RESOLUTION, f"r = {r2[0]}, status {st2[0]}")


def test_tikhonov_prior():
    """
    The regularised answer to the identifiability finding. A prior on kappa
    must (a) leave a clean fit alone when it agrees with the data, (b) collapse
    the noise-seed spread of kappa without costing fit quality, and (c) report
    what it paid when it disagrees, rather than hide it.
    """
    print("\nC3 -- Tikhonov prior on kappa")
    from calibrate.fit import prior_residuals
    from models.heston import variance_swap_rate, kappa_from_variance_swap

    S = build_surface(FAST_TAUS)
    plain = calibrate_heston(S, starts=DEFAULT_STARTS[:1])
    pinned = calibrate_heston(S, starts=DEFAULT_STARTS[:1],
                              prior={'kappa': TRUE.kappa}, prior_weight=50.0)
    check("a prior at the truth changes a clean fit by less than 0.1%",
          abs(pinned['params'].kappa - plain['params'].kappa) / TRUE.kappa < 1e-3,
          f"kappa {plain['params'].kappa:.5f} -> {pinned['params'].kappa:.5f}")
    check("prior cost is reported separately from data cost",
          'prior_cost' in pinned and 'data_cost' in pinned
          and abs(pinned['prior_cost'] + pinned['data_cost'] - pinned['cost']) < 1e-12,
          f"prior {pinned['prior_cost']:.2e}, data {pinned['data_cost']:.2e}")
    check("no prior -> zero prior cost", plain['prior_cost'] == 0.0)

    noise = 0.005
    free, reg = [], []
    for s in range(4):
        Sn = build_surface(FAST_TAUS, noise=noise, seed=s)
        free.append(calibrate_heston(Sn, starts=DEFAULT_STARTS[:1]))
        reg.append(calibrate_heston(Sn, starts=DEFAULT_STARTS[:1],
                                    prior={'kappa': TRUE.kappa}, prior_weight=50.0))

    def spread(fits, name):
        v = np.array([getattr(f['params'], name) for f in fits])
        return float(np.std(v) / abs(np.mean(v)))

    sf, sr = spread(free, 'kappa'), spread(reg, 'kappa')
    print(f"      kappa spread across noise seeds: free {sf*100:.1f}%  regularised {sr*100:.1f}%")
    check("the prior collapses the kappa spread by at least 3x", sr < sf / 3.0,
          f"{sf*100:.1f}% -> {sr*100:.1f}%")
    check("...to under 10%", sr < 0.10, f"{sr*100:.1f}%")
    rf = max(f['rmse_vol'] for f in free)
    rr = max(f['rmse_vol'] for f in reg)
    check("without costing fit quality (rmse within 10% of the free fit)",
          rr < 1.1 * rf, f"rmse {rf*100:.3f} -> {rr*100:.3f} vol points")

    # A WRONG prior must show up in the bill
    wrong = calibrate_heston(S, starts=DEFAULT_STARTS[:1],
                             prior={'kappa': 2.0 * TRUE.kappa}, prior_weight=50.0)
    check("a wrong prior pays a visible prior cost",
          wrong['prior_cost'] > 100.0 * pinned['prior_cost'] + 1e-6,
          f"prior cost {wrong['prior_cost']:.3e} vs {pinned['prior_cost']:.3e} at the truth")
    check("...and is pulled between data and prior, not to either",
          TRUE.kappa < wrong['params'].kappa < 2.0 * TRUE.kappa,
          f"kappa = {wrong['params'].kappa:.4f} between {TRUE.kappa} and {2*TRUE.kappa}")

    # prior_residuals unit behaviour
    r = prior_residuals(TRUE, HESTON_TRANSFORM, {'kappa': 1.0}, 4.0)
    check("prior residual is sqrt(lambda) * relative deviation",
          abs(r[0] - 2.0 * (TRUE.kappa - 1.0) / 1.0) < 1e-12, f"{r}")
    try:
        prior_residuals(TRUE, HESTON_TRANSFORM, {'nu': 1.0}, 1.0)
        bad = False
    except KeyError:
        bad = True
    check("a prior on an unknown parameter is refused", bad)

    # The variance-swap route to a kappa prior
    rate = variance_swap_rate(TRUE, 1.5)
    k = kappa_from_variance_swap(TRUE.v0, TRUE.theta, 1.5, rate)
    check("kappa recovered from a variance-swap rate", abs(k - TRUE.kappa) < 1e-6,
          f"{k:.8f}")
    check("an impossible rate returns None, not a number",
          kappa_from_variance_swap(TRUE.v0, TRUE.theta, 1.5, 0.5) is None)
    vs_pinned = calibrate_heston(S, starts=DEFAULT_STARTS[:1],
                                 prior={'kappa': k}, prior_weight=200.0)
    check("pinning kappa from the variance swap reproduces the truth",
          abs(vs_pinned['params'].kappa - TRUE.kappa) / TRUE.kappa < 1e-3,
          f"kappa {vs_pinned['params'].kappa:.5f}")


if __name__ == "__main__":
    print("=" * 74)
    print("Session C -- calibration")
    print("=" * 74)
    t0 = time.perf_counter()
    test_lm_driver()
    test_transform()
    test_objective()
    test_failure_is_never_cheaper()
    test_clean_recovery()
    test_multistart()
    test_identifiability()
    test_identifiability_mechanism()
    test_tikhonov_prior()
    print("\n" + "=" * 74)
    print(f"{len(PASS)} passed, {len(FAIL)} failed   ({time.perf_counter()-t0:.0f}s)")
    for f in FAIL:
        print(f"  FAILED: {f}")
    print("=" * 74)
    sys.exit(1 if FAIL else 0)
